'------------------------------------------------------------------------------
' <auto-generated>
'     這段程式碼是由工具產生的。
'     執行階段版本:4.0.30319.42000
'
'     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
'     變更將會遺失。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'原始程式碼已由 Microsoft.VSDesigner 自動產生，版本 4.0.30319.42000。
'
Namespace ITSWebc
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9221.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="twsITSWebcSoap", [Namespace]:="https://itsapi.etraining.gov.tw/ITSWebExport/")>  _
    Partial Public Class twsITSWebc
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private GetStudHis1OperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetStudHis2OperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.WDAIIP.My.MySettings.Default.WDAIIP_SYS_Net_ITSWebc_twsITSWebc
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event GetStudHis1Completed As GetStudHis1CompletedEventHandler
        
        '''<remarks/>
        Public Event GetStudHis2Completed As GetStudHis2CompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://itsapi.etraining.gov.tw/ITSWebExport/GetStudHis1", RequestNamespace:="https://itsapi.etraining.gov.tw/ITSWebExport/", ResponseNamespace:="https://itsapi.etraining.gov.tw/ITSWebExport/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetStudHis1(ByVal s_AUTH As String, ByVal s_IDNO As String, ByVal s_BIRTHDAY As String) As ResultOfSTUDENT_TRAINING_HISTORY_VIEW
            Dim results() As Object = Me.Invoke("GetStudHis1", New Object() {s_AUTH, s_IDNO, s_BIRTHDAY})
            Return CType(results(0),ResultOfSTUDENT_TRAINING_HISTORY_VIEW)
        End Function
        
        '''<remarks/>
        Public Function BeginGetStudHis1(ByVal s_AUTH As String, ByVal s_IDNO As String, ByVal s_BIRTHDAY As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("GetStudHis1", New Object() {s_AUTH, s_IDNO, s_BIRTHDAY}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndGetStudHis1(ByVal asyncResult As System.IAsyncResult) As ResultOfSTUDENT_TRAINING_HISTORY_VIEW
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),ResultOfSTUDENT_TRAINING_HISTORY_VIEW)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetStudHis1Async(ByVal s_AUTH As String, ByVal s_IDNO As String, ByVal s_BIRTHDAY As String)
            Me.GetStudHis1Async(s_AUTH, s_IDNO, s_BIRTHDAY, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetStudHis1Async(ByVal s_AUTH As String, ByVal s_IDNO As String, ByVal s_BIRTHDAY As String, ByVal userState As Object)
            If (Me.GetStudHis1OperationCompleted Is Nothing) Then
                Me.GetStudHis1OperationCompleted = AddressOf Me.OnGetStudHis1OperationCompleted
            End If
            Me.InvokeAsync("GetStudHis1", New Object() {s_AUTH, s_IDNO, s_BIRTHDAY}, Me.GetStudHis1OperationCompleted, userState)
        End Sub
        
        Private Sub OnGetStudHis1OperationCompleted(ByVal arg As Object)
            If (Not (Me.GetStudHis1CompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetStudHis1Completed(Me, New GetStudHis1CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://itsapi.etraining.gov.tw/ITSWebExport/GetStudHis2", RequestNamespace:="https://itsapi.etraining.gov.tw/ITSWebExport/", ResponseNamespace:="https://itsapi.etraining.gov.tw/ITSWebExport/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetStudHis2(ByVal s_AUTH As String, ByVal s_IDNOs As String) As ResultOfSTUDENT_TRAINING_HISTORY_VIEW
            Dim results() As Object = Me.Invoke("GetStudHis2", New Object() {s_AUTH, s_IDNOs})
            Return CType(results(0),ResultOfSTUDENT_TRAINING_HISTORY_VIEW)
        End Function
        
        '''<remarks/>
        Public Function BeginGetStudHis2(ByVal s_AUTH As String, ByVal s_IDNOs As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("GetStudHis2", New Object() {s_AUTH, s_IDNOs}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndGetStudHis2(ByVal asyncResult As System.IAsyncResult) As ResultOfSTUDENT_TRAINING_HISTORY_VIEW
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),ResultOfSTUDENT_TRAINING_HISTORY_VIEW)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetStudHis2Async(ByVal s_AUTH As String, ByVal s_IDNOs As String)
            Me.GetStudHis2Async(s_AUTH, s_IDNOs, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetStudHis2Async(ByVal s_AUTH As String, ByVal s_IDNOs As String, ByVal userState As Object)
            If (Me.GetStudHis2OperationCompleted Is Nothing) Then
                Me.GetStudHis2OperationCompleted = AddressOf Me.OnGetStudHis2OperationCompleted
            End If
            Me.InvokeAsync("GetStudHis2", New Object() {s_AUTH, s_IDNOs}, Me.GetStudHis2OperationCompleted, userState)
        End Sub
        
        Private Sub OnGetStudHis2OperationCompleted(ByVal arg As Object)
            If (Not (Me.GetStudHis2CompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetStudHis2Completed(Me, New GetStudHis2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="https://itsapi.etraining.gov.tw/ITSWebExport/")>  _
    Partial Public Class ResultOfSTUDENT_TRAINING_HISTORY_VIEW
        
        Private responseField As String
        
        Private codeField As String
        
        Private errMsgField As String
        
        Private countField As Integer
        
        Private hashCodeField As String
        
        Private recordsField() As STUDENT_TRAINING_HISTORY_VIEW
        
        '''<remarks/>
        Public Property response() As String
            Get
                Return Me.responseField
            End Get
            Set
                Me.responseField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Code() As String
            Get
                Return Me.codeField
            End Get
            Set
                Me.codeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ErrMsg() As String
            Get
                Return Me.errMsgField
            End Get
            Set
                Me.errMsgField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Count() As Integer
            Get
                Return Me.countField
            End Get
            Set
                Me.countField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property HashCode() As String
            Get
                Return Me.hashCodeField
            End Get
            Set
                Me.hashCodeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Records() As STUDENT_TRAINING_HISTORY_VIEW()
            Get
                Return Me.recordsField
            End Get
            Set
                Me.recordsField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="https://itsapi.etraining.gov.tw/ITSWebExport/")>  _
    Partial Public Class STUDENT_TRAINING_HISTORY_VIEW
        
        Private hashCodeField As String
        
        Private tPLANIDField As String
        
        Private oCIDField As Integer
        
        Private tWYEARField As Integer
        
        Private dISTIDField As String
        
        Private dISTNAMEField As String
        
        Private nTPSNOField As Integer
        
        Private nTPNAMEField As String
        
        Private bCM_SNOField As Integer
        
        Private cLASSNAMEField As String
        
        Private cYCLTYPEField As String
        
        Private bNAField As String
        
        Private bTINAMEField As String
        
        Private uP_GOV_BTINAMEField As String
        
        Private cDI_BEGIN_DATEField As Date
        
        Private cDI_END_DATEField As Date
        
        Private tHOURSField As Integer
        
        Private tPERIODField As String
        
        Private hOURRANNAMEField As String
        
        Private tRAINHOURSField As Integer
        
        Private cTTNOField As Integer
        
        Private tRAINNAMEField As String
        
        Private cGJTNOField As String
        
        Private cGJT_NAMEField As String
        
        Private sCDNOField As Integer
        
        Private sOCIDField As Integer
        
        Private iDNOField As String
        
        Private iSDuplicateField As String
        
        Private cNAMEField As String
        
        Private eNAMEField As String
        
        Private gENDERField As String
        
        Private bIRTHDAYField As Date
        
        Private cSSNOField As Integer
        
        Private cSS_STATUSField As String
        
        Private wORKSUPPIDENTField As String
        
        Private wORKSUPPIDENT_NAMEField As String
        
        Private rEJECTDAYIN14Field As String
        
        Private cJCNOField As Integer
        
        Private jOBSTATEField As Integer
        
        Private cGTIDField As String
        
        Private cGTNAMEField As String
        
        Private sUMOFMONEYField As System.Nullable(Of Decimal)
        
        Private cBTIDField As String
        
        Private cBTNAMEField As String
        
        Private aPPLIEDSTATUSMField As String
        
        Private aPPLIEDSTATUSM_NAMEField As String
        
        Private aPPLIEDSTATUSField As String
        
        Private aPPLIEDSTATUS_NAMEField As String
        
        Private aPPLIEDNOTEField As String
        
        Private aLLOTDATEField As System.Nullable(Of Date)
        
        Private eXIT_DATEField As System.Nullable(Of Date)
        
        '''<remarks/>
        Public Property HashCode() As String
            Get
                Return Me.hashCodeField
            End Get
            Set
                Me.hashCodeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property TPLANID() As String
            Get
                Return Me.tPLANIDField
            End Get
            Set
                Me.tPLANIDField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property OCID() As Integer
            Get
                Return Me.oCIDField
            End Get
            Set
                Me.oCIDField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property TWYEAR() As Integer
            Get
                Return Me.tWYEARField
            End Get
            Set
                Me.tWYEARField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property DISTID() As String
            Get
                Return Me.dISTIDField
            End Get
            Set
                Me.dISTIDField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property DISTNAME() As String
            Get
                Return Me.dISTNAMEField
            End Get
            Set
                Me.dISTNAMEField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property NTPSNO() As Integer
            Get
                Return Me.nTPSNOField
            End Get
            Set
                Me.nTPSNOField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property NTPNAME() As String
            Get
                Return Me.nTPNAMEField
            End Get
            Set
                Me.nTPNAMEField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property BCM_SNO() As Integer
            Get
                Return Me.bCM_SNOField
            End Get
            Set
                Me.bCM_SNOField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CLASSNAME() As String
            Get
                Return Me.cLASSNAMEField
            End Get
            Set
                Me.cLASSNAMEField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CYCLTYPE() As String
            Get
                Return Me.cYCLTYPEField
            End Get
            Set
                Me.cYCLTYPEField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property BNA() As String
            Get
                Return Me.bNAField
            End Get
            Set
                Me.bNAField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property BTINAME() As String
            Get
                Return Me.bTINAMEField
            End Get
            Set
                Me.bTINAMEField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property UP_GOV_BTINAME() As String
            Get
                Return Me.uP_GOV_BTINAMEField
            End Get
            Set
                Me.uP_GOV_BTINAMEField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CDI_BEGIN_DATE() As Date
            Get
                Return Me.cDI_BEGIN_DATEField
            End Get
            Set
                Me.cDI_BEGIN_DATEField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CDI_END_DATE() As Date
            Get
                Return Me.cDI_END_DATEField
            End Get
            Set
                Me.cDI_END_DATEField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property THOURS() As Integer
            Get
                Return Me.tHOURSField
            End Get
            Set
                Me.tHOURSField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property TPERIOD() As String
            Get
                Return Me.tPERIODField
            End Get
            Set
                Me.tPERIODField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property HOURRANNAME() As String
            Get
                Return Me.hOURRANNAMEField
            End Get
            Set
                Me.hOURRANNAMEField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property TRAINHOURS() As Integer
            Get
                Return Me.tRAINHOURSField
            End Get
            Set
                Me.tRAINHOURSField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CTTNO() As Integer
            Get
                Return Me.cTTNOField
            End Get
            Set
                Me.cTTNOField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property TRAINNAME() As String
            Get
                Return Me.tRAINNAMEField
            End Get
            Set
                Me.tRAINNAMEField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CGJTNO() As String
            Get
                Return Me.cGJTNOField
            End Get
            Set
                Me.cGJTNOField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CGJT_NAME() As String
            Get
                Return Me.cGJT_NAMEField
            End Get
            Set
                Me.cGJT_NAMEField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property SCDNO() As Integer
            Get
                Return Me.sCDNOField
            End Get
            Set
                Me.sCDNOField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property SOCID() As Integer
            Get
                Return Me.sOCIDField
            End Get
            Set
                Me.sOCIDField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property IDNO() As String
            Get
                Return Me.iDNOField
            End Get
            Set
                Me.iDNOField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ISDuplicate() As String
            Get
                Return Me.iSDuplicateField
            End Get
            Set
                Me.iSDuplicateField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CNAME() As String
            Get
                Return Me.cNAMEField
            End Get
            Set
                Me.cNAMEField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ENAME() As String
            Get
                Return Me.eNAMEField
            End Get
            Set
                Me.eNAMEField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property GENDER() As String
            Get
                Return Me.gENDERField
            End Get
            Set
                Me.gENDERField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property BIRTHDAY() As Date
            Get
                Return Me.bIRTHDAYField
            End Get
            Set
                Me.bIRTHDAYField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CSSNO() As Integer
            Get
                Return Me.cSSNOField
            End Get
            Set
                Me.cSSNOField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CSS_STATUS() As String
            Get
                Return Me.cSS_STATUSField
            End Get
            Set
                Me.cSS_STATUSField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property WORKSUPPIDENT() As String
            Get
                Return Me.wORKSUPPIDENTField
            End Get
            Set
                Me.wORKSUPPIDENTField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property WORKSUPPIDENT_NAME() As String
            Get
                Return Me.wORKSUPPIDENT_NAMEField
            End Get
            Set
                Me.wORKSUPPIDENT_NAMEField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property REJECTDAYIN14() As String
            Get
                Return Me.rEJECTDAYIN14Field
            End Get
            Set
                Me.rEJECTDAYIN14Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CJCNO() As Integer
            Get
                Return Me.cJCNOField
            End Get
            Set
                Me.cJCNOField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property JOBSTATE() As Integer
            Get
                Return Me.jOBSTATEField
            End Get
            Set
                Me.jOBSTATEField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CGTID() As String
            Get
                Return Me.cGTIDField
            End Get
            Set
                Me.cGTIDField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CGTNAME() As String
            Get
                Return Me.cGTNAMEField
            End Get
            Set
                Me.cGTNAMEField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property SUMOFMONEY() As System.Nullable(Of Decimal)
            Get
                Return Me.sUMOFMONEYField
            End Get
            Set
                Me.sUMOFMONEYField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CBTID() As String
            Get
                Return Me.cBTIDField
            End Get
            Set
                Me.cBTIDField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CBTNAME() As String
            Get
                Return Me.cBTNAMEField
            End Get
            Set
                Me.cBTNAMEField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property APPLIEDSTATUSM() As String
            Get
                Return Me.aPPLIEDSTATUSMField
            End Get
            Set
                Me.aPPLIEDSTATUSMField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property APPLIEDSTATUSM_NAME() As String
            Get
                Return Me.aPPLIEDSTATUSM_NAMEField
            End Get
            Set
                Me.aPPLIEDSTATUSM_NAMEField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property APPLIEDSTATUS() As String
            Get
                Return Me.aPPLIEDSTATUSField
            End Get
            Set
                Me.aPPLIEDSTATUSField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property APPLIEDSTATUS_NAME() As String
            Get
                Return Me.aPPLIEDSTATUS_NAMEField
            End Get
            Set
                Me.aPPLIEDSTATUS_NAMEField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property APPLIEDNOTE() As String
            Get
                Return Me.aPPLIEDNOTEField
            End Get
            Set
                Me.aPPLIEDNOTEField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property ALLOTDATE() As System.Nullable(Of Date)
            Get
                Return Me.aLLOTDATEField
            End Get
            Set
                Me.aLLOTDATEField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property EXIT_DATE() As System.Nullable(Of Date)
            Get
                Return Me.eXIT_DATEField
            End Get
            Set
                Me.eXIT_DATEField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9221.0")>  _
    Public Delegate Sub GetStudHis1CompletedEventHandler(ByVal sender As Object, ByVal e As GetStudHis1CompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9221.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetStudHis1CompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As ResultOfSTUDENT_TRAINING_HISTORY_VIEW
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),ResultOfSTUDENT_TRAINING_HISTORY_VIEW)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9221.0")>  _
    Public Delegate Sub GetStudHis2CompletedEventHandler(ByVal sender As Object, ByVal e As GetStudHis2CompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9221.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetStudHis2CompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As ResultOfSTUDENT_TRAINING_HISTORY_VIEW
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),ResultOfSTUDENT_TRAINING_HISTORY_VIEW)
            End Get
        End Property
    End Class
End Namespace
