'------------------------------------------------------------------------------
' <auto-generated>
'     這段程式碼是由工具產生的。
'     執行階段版本:4.0.30319.42000
'
'     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
'     變更將會遺失。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'原始程式碼已由 Microsoft.VSDesigner 自動產生，版本 4.0.30319.42000。
'
Namespace tw.gov.wda.wltims1
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9221.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="iCapWebS1Soap", [Namespace]:="http://icap.wda.gov.tw/ap/")>  _
    Partial Public Class iCapWebS1
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private Ws_onlineClass1OperationCompleted As System.Threading.SendOrPostCallback
        
        Private Ws_onlineClass2OperationCompleted As System.Threading.SendOrPostCallback
        
        Private Ws_onlineClassDiff1OperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.WDAIIP.My.MySettings.Default.WDAIIP_SYS_Net_tw_gov_wda_wltims1_iCapWebS1
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event Ws_onlineClass1Completed As Ws_onlineClass1CompletedEventHandler
        
        '''<remarks/>
        Public Event Ws_onlineClass2Completed As Ws_onlineClass2CompletedEventHandler
        
        '''<remarks/>
        Public Event Ws_onlineClassDiff1Completed As Ws_onlineClassDiff1CompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://icap.wda.gov.tw/ap/Ws_onlineClass1", RequestNamespace:="http://icap.wda.gov.tw/ap/", ResponseNamespace:="http://icap.wda.gov.tw/ap/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function Ws_onlineClass1(ByVal s_AUTH As String, ByVal ICAP As String) As String
            Dim results() As Object = Me.Invoke("Ws_onlineClass1", New Object() {s_AUTH, ICAP})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Function BeginWs_onlineClass1(ByVal s_AUTH As String, ByVal ICAP As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("Ws_onlineClass1", New Object() {s_AUTH, ICAP}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndWs_onlineClass1(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub Ws_onlineClass1Async(ByVal s_AUTH As String, ByVal ICAP As String)
            Me.Ws_onlineClass1Async(s_AUTH, ICAP, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub Ws_onlineClass1Async(ByVal s_AUTH As String, ByVal ICAP As String, ByVal userState As Object)
            If (Me.Ws_onlineClass1OperationCompleted Is Nothing) Then
                Me.Ws_onlineClass1OperationCompleted = AddressOf Me.OnWs_onlineClass1OperationCompleted
            End If
            Me.InvokeAsync("Ws_onlineClass1", New Object() {s_AUTH, ICAP}, Me.Ws_onlineClass1OperationCompleted, userState)
        End Sub
        
        Private Sub OnWs_onlineClass1OperationCompleted(ByVal arg As Object)
            If (Not (Me.Ws_onlineClass1CompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent Ws_onlineClass1Completed(Me, New Ws_onlineClass1CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://icap.wda.gov.tw/ap/Ws_onlineClass2", RequestNamespace:="http://icap.wda.gov.tw/ap/", ResponseNamespace:="http://icap.wda.gov.tw/ap/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function Ws_onlineClass2(ByVal s_AUTH As String, ByVal ICAP As String) As iCAPData
            Dim results() As Object = Me.Invoke("Ws_onlineClass2", New Object() {s_AUTH, ICAP})
            Return CType(results(0),iCAPData)
        End Function
        
        '''<remarks/>
        Public Function BeginWs_onlineClass2(ByVal s_AUTH As String, ByVal ICAP As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("Ws_onlineClass2", New Object() {s_AUTH, ICAP}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndWs_onlineClass2(ByVal asyncResult As System.IAsyncResult) As iCAPData
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),iCAPData)
        End Function
        
        '''<remarks/>
        Public Overloads Sub Ws_onlineClass2Async(ByVal s_AUTH As String, ByVal ICAP As String)
            Me.Ws_onlineClass2Async(s_AUTH, ICAP, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub Ws_onlineClass2Async(ByVal s_AUTH As String, ByVal ICAP As String, ByVal userState As Object)
            If (Me.Ws_onlineClass2OperationCompleted Is Nothing) Then
                Me.Ws_onlineClass2OperationCompleted = AddressOf Me.OnWs_onlineClass2OperationCompleted
            End If
            Me.InvokeAsync("Ws_onlineClass2", New Object() {s_AUTH, ICAP}, Me.Ws_onlineClass2OperationCompleted, userState)
        End Sub
        
        Private Sub OnWs_onlineClass2OperationCompleted(ByVal arg As Object)
            If (Not (Me.Ws_onlineClass2CompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent Ws_onlineClass2Completed(Me, New Ws_onlineClass2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://icap.wda.gov.tw/ap/Ws_onlineClassDiff1", RequestNamespace:="http://icap.wda.gov.tw/ap/", ResponseNamespace:="http://icap.wda.gov.tw/ap/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function Ws_onlineClassDiff1(ByVal s_AUTH As String, ByVal SERIAL_NUMBER As String, ByVal CLASS_ID As String, ByVal EMAIL As String, ByVal OCID As String) As String
            Dim results() As Object = Me.Invoke("Ws_onlineClassDiff1", New Object() {s_AUTH, SERIAL_NUMBER, CLASS_ID, EMAIL, OCID})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Function BeginWs_onlineClassDiff1(ByVal s_AUTH As String, ByVal SERIAL_NUMBER As String, ByVal CLASS_ID As String, ByVal EMAIL As String, ByVal OCID As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("Ws_onlineClassDiff1", New Object() {s_AUTH, SERIAL_NUMBER, CLASS_ID, EMAIL, OCID}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndWs_onlineClassDiff1(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub Ws_onlineClassDiff1Async(ByVal s_AUTH As String, ByVal SERIAL_NUMBER As String, ByVal CLASS_ID As String, ByVal EMAIL As String, ByVal OCID As String)
            Me.Ws_onlineClassDiff1Async(s_AUTH, SERIAL_NUMBER, CLASS_ID, EMAIL, OCID, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub Ws_onlineClassDiff1Async(ByVal s_AUTH As String, ByVal SERIAL_NUMBER As String, ByVal CLASS_ID As String, ByVal EMAIL As String, ByVal OCID As String, ByVal userState As Object)
            If (Me.Ws_onlineClassDiff1OperationCompleted Is Nothing) Then
                Me.Ws_onlineClassDiff1OperationCompleted = AddressOf Me.OnWs_onlineClassDiff1OperationCompleted
            End If
            Me.InvokeAsync("Ws_onlineClassDiff1", New Object() {s_AUTH, SERIAL_NUMBER, CLASS_ID, EMAIL, OCID}, Me.Ws_onlineClassDiff1OperationCompleted, userState)
        End Sub
        
        Private Sub OnWs_onlineClassDiff1OperationCompleted(ByVal arg As Object)
            If (Not (Me.Ws_onlineClassDiff1CompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent Ws_onlineClassDiff1Completed(Me, New Ws_onlineClassDiff1CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://icap.wda.gov.tw/ap/")>  _
    Partial Public Class iCAPData
        
        Private iCAPData1Field() As Course
        
        Private errMsgField As String
        
        '''<remarks/>
        Public Property iCAPData1() As Course()
            Get
                Return Me.iCAPData1Field
            End Get
            Set
                Me.iCAPData1Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ErrMsg() As String
            Get
                Return Me.errMsgField
            End Get
            Set
                Me.errMsgField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://icap.wda.gov.tw/ap/")>  _
    Partial Public Class Course
        
        Private cASE_IDField As String
        
        Private cLASS_IDField As String
        
        Private c_IDField As String
        
        Private cOMPANYField As String
        
        Private nAMEField As String
        
        Private tRAIN_COURSE_HOURSField As String
        
        Private cLASS_LEVELField As String
        
        Private tARGETField As String
        
        Private eSSENTIALField As String
        
        Private dETAILField() As Unit
        
        '''<remarks/>
        Public Property CASE_ID() As String
            Get
                Return Me.cASE_IDField
            End Get
            Set
                Me.cASE_IDField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CLASS_ID() As String
            Get
                Return Me.cLASS_IDField
            End Get
            Set
                Me.cLASS_IDField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property C_ID() As String
            Get
                Return Me.c_IDField
            End Get
            Set
                Me.c_IDField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property COMPANY() As String
            Get
                Return Me.cOMPANYField
            End Get
            Set
                Me.cOMPANYField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property NAME() As String
            Get
                Return Me.nAMEField
            End Get
            Set
                Me.nAMEField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property TRAIN_COURSE_HOURS() As String
            Get
                Return Me.tRAIN_COURSE_HOURSField
            End Get
            Set
                Me.tRAIN_COURSE_HOURSField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CLASS_LEVEL() As String
            Get
                Return Me.cLASS_LEVELField
            End Get
            Set
                Me.cLASS_LEVELField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property TARGET() As String
            Get
                Return Me.tARGETField
            End Get
            Set
                Me.tARGETField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ESSENTIAL() As String
            Get
                Return Me.eSSENTIALField
            End Get
            Set
                Me.eSSENTIALField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property DETAIL() As Unit()
            Get
                Return Me.dETAILField
            End Get
            Set
                Me.dETAILField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://icap.wda.gov.tw/ap/")>  _
    Partial Public Class Unit
        
        Private uNIT_NAMEField As String
        
        Private uNIT_HOURField As String
        
        Private tEA_EXPField As String
        
        Private sUP_EXPField As String
        
        Private tEACH_MATERIALSField As String
        
        Private tEACH_EQUIPMENTField As String
        
        Private aCTUAL_TEACHERField As String
        
        Private tEACH_METHODField As String
        
        Private eVALUATION_METHODField As String
        
        Private oUTLINEField As String
        
        Private aCTUAL_T_EXPField As String
        
        Private aCTUAL_SUPPORTField As String
        
        Private aCTUAL_S_EXPField As String
        
        '''<remarks/>
        Public Property UNIT_NAME() As String
            Get
                Return Me.uNIT_NAMEField
            End Get
            Set
                Me.uNIT_NAMEField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property UNIT_HOUR() As String
            Get
                Return Me.uNIT_HOURField
            End Get
            Set
                Me.uNIT_HOURField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property TEA_EXP() As String
            Get
                Return Me.tEA_EXPField
            End Get
            Set
                Me.tEA_EXPField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property SUP_EXP() As String
            Get
                Return Me.sUP_EXPField
            End Get
            Set
                Me.sUP_EXPField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property TEACH_MATERIALS() As String
            Get
                Return Me.tEACH_MATERIALSField
            End Get
            Set
                Me.tEACH_MATERIALSField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property TEACH_EQUIPMENT() As String
            Get
                Return Me.tEACH_EQUIPMENTField
            End Get
            Set
                Me.tEACH_EQUIPMENTField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ACTUAL_TEACHER() As String
            Get
                Return Me.aCTUAL_TEACHERField
            End Get
            Set
                Me.aCTUAL_TEACHERField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property TEACH_METHOD() As String
            Get
                Return Me.tEACH_METHODField
            End Get
            Set
                Me.tEACH_METHODField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property EVALUATION_METHOD() As String
            Get
                Return Me.eVALUATION_METHODField
            End Get
            Set
                Me.eVALUATION_METHODField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property OUTLINE() As String
            Get
                Return Me.oUTLINEField
            End Get
            Set
                Me.oUTLINEField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ACTUAL_T_EXP() As String
            Get
                Return Me.aCTUAL_T_EXPField
            End Get
            Set
                Me.aCTUAL_T_EXPField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ACTUAL_SUPPORT() As String
            Get
                Return Me.aCTUAL_SUPPORTField
            End Get
            Set
                Me.aCTUAL_SUPPORTField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ACTUAL_S_EXP() As String
            Get
                Return Me.aCTUAL_S_EXPField
            End Get
            Set
                Me.aCTUAL_S_EXPField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9221.0")>  _
    Public Delegate Sub Ws_onlineClass1CompletedEventHandler(ByVal sender As Object, ByVal e As Ws_onlineClass1CompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9221.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class Ws_onlineClass1CompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9221.0")>  _
    Public Delegate Sub Ws_onlineClass2CompletedEventHandler(ByVal sender As Object, ByVal e As Ws_onlineClass2CompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9221.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class Ws_onlineClass2CompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As iCAPData
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),iCAPData)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9221.0")>  _
    Public Delegate Sub Ws_onlineClassDiff1CompletedEventHandler(ByVal sender As Object, ByVal e As Ws_onlineClassDiff1CompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9221.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class Ws_onlineClassDiff1CompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
End Namespace
