'------------------------------------------------------------------------------
' <auto-generated>
'     這段程式碼是由工具產生的。
'     執行階段版本:4.0.30319.42000
'
'     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
'     變更將會遺失。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'原始程式碼已由 Microsoft.VSDesigner 自動產生，版本 4.0.30319.42000。
'
Namespace tw.gov.wda.wltims2
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9221.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="TeacherSchedulesSoap", [Namespace]:="http://wltims.Wdaline/TeacherSchedules")>  _
    Partial Public Class TeacherSchedules
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private SearchAttendanceOperationCompleted As System.Threading.SendOrPostCallback
        
        Private SearchAttendanceROperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.WDAIIP.My.MySettings.Default.WDAIIP_SYS_Net_tw_gov_wda_wltims2_TeacherSchedules
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event SearchAttendanceCompleted As SearchAttendanceCompletedEventHandler
        
        '''<remarks/>
        Public Event SearchAttendanceRCompleted As SearchAttendanceRCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://wltims.Wdaline/TeacherSchedules/SearchAttendance", RequestNamespace:="http://wltims.Wdaline/TeacherSchedules", ResponseNamespace:="http://wltims.Wdaline/TeacherSchedules", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function SearchAttendance(ByVal s_OCID As String, ByVal s_CourseDate As String) As ResultOfListOfTeacherAttendanceResponse
            Dim results() As Object = Me.Invoke("SearchAttendance", New Object() {s_OCID, s_CourseDate})
            Return CType(results(0),ResultOfListOfTeacherAttendanceResponse)
        End Function
        
        '''<remarks/>
        Public Function BeginSearchAttendance(ByVal s_OCID As String, ByVal s_CourseDate As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("SearchAttendance", New Object() {s_OCID, s_CourseDate}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndSearchAttendance(ByVal asyncResult As System.IAsyncResult) As ResultOfListOfTeacherAttendanceResponse
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),ResultOfListOfTeacherAttendanceResponse)
        End Function
        
        '''<remarks/>
        Public Overloads Sub SearchAttendanceAsync(ByVal s_OCID As String, ByVal s_CourseDate As String)
            Me.SearchAttendanceAsync(s_OCID, s_CourseDate, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub SearchAttendanceAsync(ByVal s_OCID As String, ByVal s_CourseDate As String, ByVal userState As Object)
            If (Me.SearchAttendanceOperationCompleted Is Nothing) Then
                Me.SearchAttendanceOperationCompleted = AddressOf Me.OnSearchAttendanceOperationCompleted
            End If
            Me.InvokeAsync("SearchAttendance", New Object() {s_OCID, s_CourseDate}, Me.SearchAttendanceOperationCompleted, userState)
        End Sub
        
        Private Sub OnSearchAttendanceOperationCompleted(ByVal arg As Object)
            If (Not (Me.SearchAttendanceCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent SearchAttendanceCompleted(Me, New SearchAttendanceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://wltims.Wdaline/TeacherSchedules/SearchAttendanceR", RequestNamespace:="http://wltims.Wdaline/TeacherSchedules", ResponseNamespace:="http://wltims.Wdaline/TeacherSchedules", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function SearchAttendanceR(ByVal s_OCID As String, ByVal s_CourseDate As String) As String
            Dim results() As Object = Me.Invoke("SearchAttendanceR", New Object() {s_OCID, s_CourseDate})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Function BeginSearchAttendanceR(ByVal s_OCID As String, ByVal s_CourseDate As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("SearchAttendanceR", New Object() {s_OCID, s_CourseDate}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndSearchAttendanceR(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub SearchAttendanceRAsync(ByVal s_OCID As String, ByVal s_CourseDate As String)
            Me.SearchAttendanceRAsync(s_OCID, s_CourseDate, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub SearchAttendanceRAsync(ByVal s_OCID As String, ByVal s_CourseDate As String, ByVal userState As Object)
            If (Me.SearchAttendanceROperationCompleted Is Nothing) Then
                Me.SearchAttendanceROperationCompleted = AddressOf Me.OnSearchAttendanceROperationCompleted
            End If
            Me.InvokeAsync("SearchAttendanceR", New Object() {s_OCID, s_CourseDate}, Me.SearchAttendanceROperationCompleted, userState)
        End Sub
        
        Private Sub OnSearchAttendanceROperationCompleted(ByVal arg As Object)
            If (Not (Me.SearchAttendanceRCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent SearchAttendanceRCompleted(Me, New SearchAttendanceRCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://wltims.Wdaline/TeacherSchedules")>  _
    Partial Public Class ResultOfListOfTeacherAttendanceResponse
        
        Private resultsField() As TeacherAttendanceResponse
        
        Private errorCodeField As String
        
        Private errorMessageField As String
        
        '''<remarks/>
        Public Property Results() As TeacherAttendanceResponse()
            Get
                Return Me.resultsField
            End Get
            Set
                Me.resultsField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ErrorCode() As String
            Get
                Return Me.errorCodeField
            End Get
            Set
                Me.errorCodeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ErrorMessage() As String
            Get
                Return Me.errorMessageField
            End Get
            Set
                Me.errorMessageField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://wltims.Wdaline/TeacherSchedules")>  _
    Partial Public Class TeacherAttendanceResponse
        
        Private lIDField As String
        
        Private branchCodeField As String
        
        Private branchValueField As String
        
        Private groupCodeField As String
        
        Private groupNameField As String
        
        Private classCodeField As String
        
        Private classNameField As String
        
        Private courseSerialNumberField As String
        
        Private courseNameField As String
        
        Private teacherIdentityField As String
        
        Private teacherNameField As String
        
        Private signMethodField As Integer
        
        Private signTypeField As Integer
        
        Private signedTimeField As String
        
        Private updatedTimeField As String
        
        '''<remarks/>
        Public Property LID() As String
            Get
                Return Me.lIDField
            End Get
            Set
                Me.lIDField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property BranchCode() As String
            Get
                Return Me.branchCodeField
            End Get
            Set
                Me.branchCodeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property BranchValue() As String
            Get
                Return Me.branchValueField
            End Get
            Set
                Me.branchValueField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property GroupCode() As String
            Get
                Return Me.groupCodeField
            End Get
            Set
                Me.groupCodeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property GroupName() As String
            Get
                Return Me.groupNameField
            End Get
            Set
                Me.groupNameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ClassCode() As String
            Get
                Return Me.classCodeField
            End Get
            Set
                Me.classCodeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ClassName() As String
            Get
                Return Me.classNameField
            End Get
            Set
                Me.classNameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CourseSerialNumber() As String
            Get
                Return Me.courseSerialNumberField
            End Get
            Set
                Me.courseSerialNumberField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CourseName() As String
            Get
                Return Me.courseNameField
            End Get
            Set
                Me.courseNameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property TeacherIdentity() As String
            Get
                Return Me.teacherIdentityField
            End Get
            Set
                Me.teacherIdentityField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property TeacherName() As String
            Get
                Return Me.teacherNameField
            End Get
            Set
                Me.teacherNameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property SignMethod() As Integer
            Get
                Return Me.signMethodField
            End Get
            Set
                Me.signMethodField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property SignType() As Integer
            Get
                Return Me.signTypeField
            End Get
            Set
                Me.signTypeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property SignedTime() As String
            Get
                Return Me.signedTimeField
            End Get
            Set
                Me.signedTimeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property UpdatedTime() As String
            Get
                Return Me.updatedTimeField
            End Get
            Set
                Me.updatedTimeField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9221.0")>  _
    Public Delegate Sub SearchAttendanceCompletedEventHandler(ByVal sender As Object, ByVal e As SearchAttendanceCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9221.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class SearchAttendanceCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As ResultOfListOfTeacherAttendanceResponse
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),ResultOfListOfTeacherAttendanceResponse)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9221.0")>  _
    Public Delegate Sub SearchAttendanceRCompletedEventHandler(ByVal sender As Object, ByVal e As SearchAttendanceRCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9221.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class SearchAttendanceRCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
End Namespace
