'------------------------------------------------------------------------------
' <auto-generated>
'     這段程式碼是由工具產生的。
'     執行階段版本:4.0.30319.42000
'
'     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
'     變更將會遺失。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.14.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "My.Settings 自動儲存功能"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(sender As Global.System.Object, e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("https://wltims.wda.gov.tw/GetJobMail3/Service1.asmx")>  _
        Public ReadOnly Property WDAIIP_SYS_Net_SendMailws3_Service1() As String
            Get
                Return CType(Me("WDAIIP_SYS_Net_SendMailws3_Service1"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("https://wltims.wda.gov.tw/ITSWebc/twsITSWebc.asmx")>  _
        Public ReadOnly Property WDAIIP_SYS_Net_ITSWebc_twsITSWebc() As String
            Get
                Return CType(Me("WDAIIP_SYS_Net_ITSWebc_twsITSWebc"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("https://wltims.wda.gov.tw/TIMSWS/timsService1.asmx")>  _
        Public ReadOnly Property WDAIIP_SYS_Net_timsService1_timsService1() As String
            Get
                Return CType(Me("WDAIIP_SYS_Net_timsService1_timsService1"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("https://wltims.wda.gov.tw/bli_wsv4/get_data3.asmx")>  _
        Public ReadOnly Property WDAIIP_SYS_Net_bli_wsv4_get_data3() As String
            Get
                Return CType(Me("WDAIIP_SYS_Net_bli_wsv4_get_data3"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("https://wltims.wda.gov.tw/WdaLine/StudentSchedules.asmx")>  _
        Public ReadOnly Property WDAIIP_SYS_Net_tw_gov_wda_wltims_StudentSchedules() As String
            Get
                Return CType(Me("WDAIIP_SYS_Net_tw_gov_wda_wltims_StudentSchedules"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("https://wltims.wda.gov.tw/iCapWeb/iCapWebS1.asmx")>  _
        Public ReadOnly Property WDAIIP_SYS_Net_tw_gov_wda_wltims1_iCapWebS1() As String
            Get
                Return CType(Me("WDAIIP_SYS_Net_tw_gov_wda_wltims1_iCapWebS1"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("https://wltims.wda.gov.tw/WdaLine/TeacherSchedules.asmx")>  _
        Public ReadOnly Property WDAIIP_SYS_Net_tw_gov_wda_wltims2_TeacherSchedules() As String
            Get
                Return CType(Me("WDAIIP_SYS_Net_tw_gov_wda_wltims2_TeacherSchedules"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("https://wltims.wda.gov.tw/GetJobMail3/ttqs_service_1.asmx")>  _
        Public ReadOnly Property WDAIIP_SYS_Net_ttqsservice1_ttqs_service_1() As String
            Get
                Return CType(Me("WDAIIP_SYS_Net_ttqsservice1_ttqs_service_1"),String)
            End Get
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.WDAIIP.My.MySettings
            Get
                Return Global.WDAIIP.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
