'------------------------------------------------------------------------------
' <auto-generated>
'     這段程式碼是由工具產生的。
'     執行階段版本:4.0.30319.42000
'
'     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
'     變更將會遺失。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'原始程式碼已由 Microsoft.VSDesigner 自動產生，版本 4.0.30319.42000。
'
Namespace bli_wsv4
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9221.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="get_data3Soap", [Namespace]:="http://tempuri.org/bli_wsv/get_data3")>  _
    Partial Public Class get_data3
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private get_detailOperationCompleted As System.Threading.SendOrPostCallback
        
        Private get_pensonOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.WDAIIP.My.MySettings.Default.WDAIIP_SYS_Net_bli_wsv4_get_data3
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event get_detailCompleted As get_detailCompletedEventHandler
        
        '''<remarks/>
        Public Event get_pensonCompleted As get_pensonCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/bli_wsv/get_data3/get_detail", RequestNamespace:="http://tempuri.org/bli_wsv/get_data3", ResponseNamespace:="http://tempuri.org/bli_wsv/get_data3", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function get_detail(ByVal sysname As String, ByVal IDN As String, ByVal Iname As String, ByVal birthday As String, ByVal utype As String, ByVal begin_date As String, ByVal end_date As String) As String
            Dim results() As Object = Me.Invoke("get_detail", New Object() {sysname, IDN, Iname, birthday, utype, begin_date, end_date})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Function Beginget_detail(ByVal sysname As String, ByVal IDN As String, ByVal Iname As String, ByVal birthday As String, ByVal utype As String, ByVal begin_date As String, ByVal end_date As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("get_detail", New Object() {sysname, IDN, Iname, birthday, utype, begin_date, end_date}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function Endget_detail(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub get_detailAsync(ByVal sysname As String, ByVal IDN As String, ByVal Iname As String, ByVal birthday As String, ByVal utype As String, ByVal begin_date As String, ByVal end_date As String)
            Me.get_detailAsync(sysname, IDN, Iname, birthday, utype, begin_date, end_date, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub get_detailAsync(ByVal sysname As String, ByVal IDN As String, ByVal Iname As String, ByVal birthday As String, ByVal utype As String, ByVal begin_date As String, ByVal end_date As String, ByVal userState As Object)
            If (Me.get_detailOperationCompleted Is Nothing) Then
                Me.get_detailOperationCompleted = AddressOf Me.Onget_detailOperationCompleted
            End If
            Me.InvokeAsync("get_detail", New Object() {sysname, IDN, Iname, birthday, utype, begin_date, end_date}, Me.get_detailOperationCompleted, userState)
        End Sub
        
        Private Sub Onget_detailOperationCompleted(ByVal arg As Object)
            If (Not (Me.get_detailCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent get_detailCompleted(Me, New get_detailCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/bli_wsv/get_data3/get_penson", RequestNamespace:="http://tempuri.org/bli_wsv/get_data3", ResponseNamespace:="http://tempuri.org/bli_wsv/get_data3", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function get_penson(ByVal sysname As String, ByVal IDN As String, ByVal Iname As String, ByVal birthday As String, ByVal uno As String, ByVal begin_date As String, ByVal end_date As String) As String
            Dim results() As Object = Me.Invoke("get_penson", New Object() {sysname, IDN, Iname, birthday, uno, begin_date, end_date})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Function Beginget_penson(ByVal sysname As String, ByVal IDN As String, ByVal Iname As String, ByVal birthday As String, ByVal uno As String, ByVal begin_date As String, ByVal end_date As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("get_penson", New Object() {sysname, IDN, Iname, birthday, uno, begin_date, end_date}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function Endget_penson(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub get_pensonAsync(ByVal sysname As String, ByVal IDN As String, ByVal Iname As String, ByVal birthday As String, ByVal uno As String, ByVal begin_date As String, ByVal end_date As String)
            Me.get_pensonAsync(sysname, IDN, Iname, birthday, uno, begin_date, end_date, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub get_pensonAsync(ByVal sysname As String, ByVal IDN As String, ByVal Iname As String, ByVal birthday As String, ByVal uno As String, ByVal begin_date As String, ByVal end_date As String, ByVal userState As Object)
            If (Me.get_pensonOperationCompleted Is Nothing) Then
                Me.get_pensonOperationCompleted = AddressOf Me.Onget_pensonOperationCompleted
            End If
            Me.InvokeAsync("get_penson", New Object() {sysname, IDN, Iname, birthday, uno, begin_date, end_date}, Me.get_pensonOperationCompleted, userState)
        End Sub
        
        Private Sub Onget_pensonOperationCompleted(ByVal arg As Object)
            If (Not (Me.get_pensonCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent get_pensonCompleted(Me, New get_pensonCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9221.0")>  _
    Public Delegate Sub get_detailCompletedEventHandler(ByVal sender As Object, ByVal e As get_detailCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9221.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class get_detailCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9221.0")>  _
    Public Delegate Sub get_pensonCompletedEventHandler(ByVal sender As Object, ByVal e As get_pensonCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9221.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class get_pensonCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
End Namespace
