'------------------------------------------------------------------------------
' <auto-generated>
'     這段程式碼是由工具產生的。
'     執行階段版本:4.0.30319.42000
'
'     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
'     變更將會遺失。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'原始程式碼已由 Microsoft.VSDesigner 自動產生，版本 4.0.30319.42000。
'
Namespace timsService1
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9221.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="timsService1Soap", [Namespace]:="https://wltims/TIMSWS/timsService1")>  _
    Partial Public Class timsService1
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private ChkStudDoubleOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ChkStudDouble2OperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.WDAIIP.My.MySettings.Default.WDAIIP_SYS_Net_timsService1_timsService1
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event ChkStudDoubleCompleted As ChkStudDoubleCompletedEventHandler
        
        '''<remarks/>
        Public Event ChkStudDouble2Completed As ChkStudDouble2CompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://wltims/TIMSWS/timsService1/ChkStudDouble", RequestNamespace:="https://wltims/TIMSWS/timsService1", ResponseNamespace:="https://wltims/TIMSWS/timsService1", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ChkStudDouble(ByVal IDNO As String, ByVal OCID1 As String) As String
            Dim results() As Object = Me.Invoke("ChkStudDouble", New Object() {IDNO, OCID1})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Function BeginChkStudDouble(ByVal IDNO As String, ByVal OCID1 As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("ChkStudDouble", New Object() {IDNO, OCID1}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndChkStudDouble(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ChkStudDoubleAsync(ByVal IDNO As String, ByVal OCID1 As String)
            Me.ChkStudDoubleAsync(IDNO, OCID1, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ChkStudDoubleAsync(ByVal IDNO As String, ByVal OCID1 As String, ByVal userState As Object)
            If (Me.ChkStudDoubleOperationCompleted Is Nothing) Then
                Me.ChkStudDoubleOperationCompleted = AddressOf Me.OnChkStudDoubleOperationCompleted
            End If
            Me.InvokeAsync("ChkStudDouble", New Object() {IDNO, OCID1}, Me.ChkStudDoubleOperationCompleted, userState)
        End Sub
        
        Private Sub OnChkStudDoubleOperationCompleted(ByVal arg As Object)
            If (Not (Me.ChkStudDoubleCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ChkStudDoubleCompleted(Me, New ChkStudDoubleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://wltims/TIMSWS/timsService1/ChkStudDouble2", RequestNamespace:="https://wltims/TIMSWS/timsService1", ResponseNamespace:="https://wltims/TIMSWS/timsService1", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ChkStudDouble2(ByVal xStudInfo As String) As String
            Dim results() As Object = Me.Invoke("ChkStudDouble2", New Object() {xStudInfo})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Function BeginChkStudDouble2(ByVal xStudInfo As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("ChkStudDouble2", New Object() {xStudInfo}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndChkStudDouble2(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ChkStudDouble2Async(ByVal xStudInfo As String)
            Me.ChkStudDouble2Async(xStudInfo, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ChkStudDouble2Async(ByVal xStudInfo As String, ByVal userState As Object)
            If (Me.ChkStudDouble2OperationCompleted Is Nothing) Then
                Me.ChkStudDouble2OperationCompleted = AddressOf Me.OnChkStudDouble2OperationCompleted
            End If
            Me.InvokeAsync("ChkStudDouble2", New Object() {xStudInfo}, Me.ChkStudDouble2OperationCompleted, userState)
        End Sub
        
        Private Sub OnChkStudDouble2OperationCompleted(ByVal arg As Object)
            If (Not (Me.ChkStudDouble2CompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ChkStudDouble2Completed(Me, New ChkStudDouble2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9221.0")>  _
    Public Delegate Sub ChkStudDoubleCompletedEventHandler(ByVal sender As Object, ByVal e As ChkStudDoubleCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9221.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ChkStudDoubleCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9221.0")>  _
    Public Delegate Sub ChkStudDouble2CompletedEventHandler(ByVal sender As Object, ByVal e As ChkStudDouble2CompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9221.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ChkStudDouble2CompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
End Namespace
